/**
 * FSM events — 4 discriminated union covering the full graph lifecycle.
 *
 * Layer 1 — pure type definitions, zero Effect dependency, zero I/O.
 * Events are generated by the api/ layer based on agent reports.
 *
 * @module
 */

/**
 * FSM event discriminated union — 4 event types covering graph lifecycle.
 *
 * Event provenance:
 * - START        → api/crud.graphStart()
 * - COMPLETE     → api/crud.graphAdvance() for agent/approval nodes (normal completion, or skip:true from when guard)
 */
export type FsmEvent =
  | { readonly type: 'START'; readonly graphName: string; readonly args?: Record<string, unknown> }
  | { readonly type: 'COMPLETE'; readonly phaseId: string; readonly durationMs: number; readonly skip?: boolean }
  | { readonly type: 'JUMP'; readonly targetPhaseId: string }
  | { readonly type: 'FORCE_END' };
